# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'pim/kimap': '@same'
    'pim/kmailtransport': '@same'
    'pim/libksieve': '@same'
    'pim/pimcommon': '@same'
    'frameworks/kxmlgui': '@latest-kf6'
    'third-party/qtkeychain': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
 tests-run-in-parallel: True
