version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "pim-sieve-editor"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/pim-sieve-editor"

[[annotations]]
path = [".gersemirc", "src/importwizard/autotests/data/**", "MAINTAINERS", "doc/**", "src/icons/**", "REUSE.toml", "src/data/MacOSXBundleInfo.plist.in"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["README-pre-commit.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["CMakePresets.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["src/data/sieveeditor-internal-tools.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"
